<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'United States', 'code' => 'US'],
            ['name' => 'Canada', 'code' => 'CA'],
            ['name' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Akrotiri', 'code' => 'AX'],
            ['name' => 'Albania', 'code' => 'AL'],
            ['name' => 'Algeria', 'code' => 'AG'],
            ['name' => 'American Samoa', 'code' => 'AQ'],
            ['name' => 'Andorra', 'code' => 'AN'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Anguilla', 'code' => 'AV'],
            ['name' => 'Antarctica', 'code' => 'AY'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AC'],
            ['name' => 'Argentina', 'code' => 'AR'],
            ['name' => 'Armenia', 'code' => 'AM'],
            ['name' => 'Aruba', 'code' => 'AA'],
            ['name' => 'Ashmore and Cartier Islands', 'code' => 'AT'],
            ['name' => 'Australia', 'code' => 'AS'],
            ['name' => 'Austria', 'code' => 'AU'],
            ['name' => 'Azerbaijan', 'code' => 'AJ'],
            ['name' => 'Bahamas', 'code' => 'BF'],
            ['name' => 'Bahrain', 'code' => 'BA'],
            ['name' => 'Baker Island', 'code' => 'FQ'],
            ['name' => 'Bangladesh', 'code' => 'BG'],
            ['name' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Belarus', 'code' => 'BO'],
            ['name' => 'Belgium', 'code' => 'BE'],
            ['name' => 'Belize', 'code' => 'BH'],
            ['name' => 'Benin', 'code' => 'BN'],
            ['name' => 'Bermuda', 'code' => 'BD'],
            ['name' => 'Bhutan', 'code' => 'BT'],
            ['name' => 'Bolivia', 'code' => 'BL'],
            ['name' => 'Bosnia-Herzegovina', 'code' => 'BK'],
            ['name' => 'Botswana', 'code' => 'BC'],
            ['name' => 'Bouvet Island', 'code' => 'BV'],
            ['name' => 'Brazil', 'code' => 'BR'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO'],
            ['name' => 'British Virgin Islands', 'code' => 'VI'],
            ['name' => 'Brunei', 'code' => 'BX'],
            ['name' => 'Bulgaria', 'code' => 'BU'],
            ['name' => 'Burkina Faso', 'code' => 'UV'],
            ['name' => 'Burma', 'code' => 'BM'],
            ['name' => 'Burundi', 'code' => 'BY'],
            ['name' => 'Cambodia', 'code' => 'CB'],
            ['name' => 'Cameroon', 'code' => 'CM'],
            ['name' => 'Cape Verde', 'code' => 'CV'],
            ['name' => 'Cayman Islands', 'code' => 'CJ'],
            ['name' => 'Central African Republic', 'code' => 'CT'],
            ['name' => 'Chad', 'code' => 'CD'],
            ['name' => 'Chile', 'code' => 'CI'],
            ['name' => 'China', 'code' => 'CH'],
            ['name' => 'Christmas Island', 'code' => 'KT'],
            ['name' => 'Clipperton Island', 'code' => 'IP'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CK'],
            ['name' => 'Colombia', 'code' => 'CO'],
            ['name' => 'Comoros', 'code' => 'CN'],
            ['name' => 'Congo (Brazzaville)', 'code' => 'CF'],
            ['name' => 'Congo (Kinshasa)', 'code' => 'CG'],
            ['name' => 'Cook Islands', 'code' => 'CW'],
            ['name' => 'Coral Sea Islands', 'code' => 'CR'],
            ['name' => 'Costa Rica', 'code' => 'CS'],
            ['name' => "Cote D'Ivoire (Ivory Coast)", 'code' => 'IV'],
            ['name' => 'Croatia', 'code' => 'HR'],
            ['name' => 'Cuba', 'code' => 'CU'],
            ['name' => 'Curacao', 'code' => 'UC'],
            ['name' => 'Cyprus', 'code' => 'CY'],
            ['name' => 'Czech Republic', 'code' => 'EZ'],
            ['name' => 'Denmark', 'code' => 'DA'],
            ['name' => 'Dhekelia', 'code' => 'DX'],
            ['name' => 'Djibouti', 'code' => 'DJ'],
            ['name' => 'Dominica', 'code' => 'DO'],
            ['name' => 'Dominican Republic', 'code' => 'DR'],
            ['name' => 'East Timor', 'code' => 'TT'],
            ['name' => 'Ecuador', 'code' => 'EC'],
            ['name' => 'Egypt', 'code' => 'EG'],
            ['name' => 'El Salvador', 'code' => 'ES'],
            ['name' => 'Equatorial Guinea', 'code' => 'EK'],
            ['name' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Estonia', 'code' => 'EN'],
            ['name' => 'Ethiopia', 'code' => 'ET'],
            ['name' => 'Falkland Islands (Islas Malvinas)', 'code' => 'FK'],
            ['name' => 'Faroe Islands', 'code' => 'FO'],
            ['name' => 'Federated States of Micronesia', 'code' => 'FM'],
            ['name' => 'Fiji', 'code' => 'FJ'],
            ['name' => 'Finland', 'code' => 'FI'],
            ['name' => 'France', 'code' => 'FR'],
            ['name' => 'French Polynesia', 'code' => 'FP'],
            ['name' => 'French Southern and Antarctic Lands', 'code' => 'FS'],
            ['name' => 'Gabon', 'code' => 'GB'],
            ['name' => 'The Gambia', 'code' => 'GA'],
            ['name' => 'Georgia', 'code' => 'GG'],
            ['name' => 'Germany', 'code' => 'GM'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Gibraltar', 'code' => 'GI'],
            ['name' => 'Greece', 'code' => 'GR'],
            ['name' => 'Greenland', 'code' => 'GL'],
            ['name' => 'Grenada', 'code' => 'GJ'],
            ['name' => 'Guam', 'code' => 'GQ'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Guernsey', 'code' => 'GK'],
            ['name' => 'Guinea', 'code' => 'GV'],
            ['name' => 'Guinea-Bissau', 'code' => 'PU'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Haiti', 'code' => 'HA'],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HM'],
            ['name' => 'Holy See', 'code' => 'VT'],
            ['name' => 'Honduras', 'code' => 'HO'],
            ['name' => 'Hong Kong', 'code' => 'HK'],
            ['name' => 'Howland Island', 'code' => 'HQ'],
            ['name' => 'Hungary', 'code' => 'HU'],
            ['name' => 'Iceland', 'code' => 'IC'],
            ['name' => 'India', 'code' => 'IN'],
            ['name' => 'Indonesia', 'code' => 'ID'],
            ['name' => 'Iran', 'code' => 'IR'],
            ['name' => 'Iraq', 'code' => 'IZ'],
            ['name' => 'Ireland', 'code' => 'EI'],
            ['name' => 'Israel', 'code' => 'IS'],
            ['name' => 'Italy', 'code' => 'IT'],
            ['name' => 'Jamaica', 'code' => 'JM'],
            ['name' => 'Jan Mayen', 'code' => 'JN'],
            ['name' => 'Japan', 'code' => 'JA'],
            ['name' => 'Jarvis Island', 'code' => 'DQ'],
            ['name' => 'Jersey', 'code' => 'JE'],
            ['name' => 'Johnston Atoll', 'code' => 'JQ'],
            ['name' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Kingman Reef', 'code' => 'KQ'],
            ['name' => 'Kiribati', 'code' => 'KR'],
            ['name' => "Korea, Democratic People's Republic of (North)", 'code' => 'KN'],
            ['name' => 'Korea, Republic of (South)', 'code' => 'KS'],
            ['name' => 'Kosovo', 'code' => 'KV'],
            ['name' => 'Kuwait', 'code' => 'KU'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'Laos', 'code' => 'LA'],
            ['name' => 'Latvia', 'code' => 'LG'],
            ['name' => 'Lebanon', 'code' => 'LE'],
            ['name' => 'Lesotho', 'code' => 'LT'],
            ['name' => 'Liberia', 'code' => 'LI'],
            ['name' => 'Libya', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'code' => 'LS'],
            ['name' => 'Lithuania', 'code' => 'LH'],
            ['name' => 'Luxembourg', 'code' => 'LU'],
            ['name' => 'Macau', 'code' => 'MC'],
            ['name' => 'Macedonia', 'code' => 'MK'],
            ['name' => 'Madagascar', 'code' => 'MA'],
            ['name' => 'Malawi', 'code' => 'MI'],
            ['name' => 'Malaysia', 'code' => 'MY'],
            ['name' => 'Maldives', 'code' => 'MV'],
            ['name' => 'Mali', 'code' => 'ML'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Man, Isle of', 'code' => 'IM'],
            ['name' => 'Marshall Islands', 'code' => 'RM'],
            ['name' => 'Mauritania', 'code' => 'MR'],
            ['name' => 'Mauritius', 'code' => 'MP'],
            ['name' => 'Mayotte', 'code' => 'MF'],
            ['name' => 'Mexico', 'code' => 'MX'],
            ['name' => 'Midway Islands', 'code' => 'MQ'],
            ['name' => 'Moldova', 'code' => 'MD'],
            ['name' => 'Monaco', 'code' => 'MN'],
            ['name' => 'Mongolia', 'code' => 'MG'],
            ['name' => 'Montenegro', 'code' => 'MJ'],
            ['name' => 'Montserrat', 'code' => 'MH'],
            ['name' => 'Morocco', 'code' => 'MO'],
            ['name' => 'Mozambique', 'code' => 'MZ'],
            ['name' => 'Namibia', 'code' => 'WA'],
            ['name' => 'Nauru', 'code' => 'NR'],
            ['name' => 'Navassa Island', 'code' => 'BQ'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Netherlands', 'code' => 'NL'],
            ['name' => 'New Caledonia', 'code' => 'NC'],
            ['name' => 'New Zealand', 'code' => 'NZ'],
            ['name' => 'Nicaragua', 'code' => 'NU'],
            ['name' => 'Niger', 'code' => 'NG'],
            ['name' => 'Nigeria', 'code' => 'NI'],
            ['name' => 'Niue', 'code' => 'NE'],
            ['name' => 'Norfolk Island', 'code' => 'NF'],
            ['name' => 'Northern Mariana Islands', 'code' => 'CQ'],
            ['name' => 'Norway', 'code' => 'NO'],
            ['name' => 'Oman', 'code' => 'MU'],
            ['name' => 'Other Country', 'code' => 'OC'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Palau', 'code' => 'PS'],
            ['name' => 'Palmyra Atoll', 'code' => 'LQ'],
            ['name' => 'Panama', 'code' => 'PM'],
            ['name' => 'Papua-New Guinea', 'code' => 'PP'],
            ['name' => 'Paracel Islands', 'code' => 'PF'],
            ['name' => 'Paraguay', 'code' => 'PA'],
            ['name' => 'Peru', 'code' => 'PE'],
            ['name' => 'Philippines', 'code' => 'RP'],
            ['name' => 'Pitcairn Islands', 'code' => 'PC'],
            ['name' => 'Poland', 'code' => 'PL'],
            ['name' => 'Portugal', 'code' => 'PO'],
            ['name' => 'Puerto Rico', 'code' => 'RQ'],
            ['name' => 'Qatar', 'code' => 'QA'],
            ['name' => 'Romania', 'code' => 'RO'],
            ['name' => 'Russia', 'code' => 'RS'],
            ['name' => 'Rwanda', 'code' => 'RW'],
            ['name' => 'Saint Barthelemy', 'code' => 'TB'],
            ['name' => 'Saint Martin', 'code' => 'RN'],
            ['name' => 'Samoa', 'code' => 'WS'],
            ['name' => 'San Marino', 'code' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'code' => 'TP'],
            ['name' => 'Saudi Arabia', 'code' => 'SA'],
            ['name' => 'Senegal', 'code' => 'SG'],
            ['name' => 'Serbia', 'code' => 'RI'],
            ['name' => 'Seychelles', 'code' => 'SE'],
            ['name' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Singapore', 'code' => 'SN'],
            ['name' => 'Sint Maarten', 'code' => 'NN'],
            ['name' => 'Slovakia', 'code' => 'LO'],
            ['name' => 'Slovenia', 'code' => 'SI'],
            ['name' => 'Solomon Islands', 'code' => 'BP'],
            ['name' => 'Somalia', 'code' => 'SO'],
            ['name' => 'South Africa', 'code' => 'SF'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'SX'],
            ['name' => 'South Sudan', 'code' => 'OD'],
            ['name' => 'Spain', 'code' => 'SP'],
            ['name' => 'Spratly Islands', 'code' => 'PG'],
            ['name' => 'Sri Lanka', 'code' => 'CE'],
            ['name' => 'St. Helena', 'code' => 'SH'],
            ['name' => 'St. Kitts and Nevis', 'code' => 'SC'],
            ['name' => 'St. Lucia Island', 'code' => 'ST'],
            ['name' => 'St. Pierre and Miquelon', 'code' => 'SB'],
            ['name' => 'St. Vincent and the Grenadines', 'code' => 'VC'],
            ['name' => 'Sudan', 'code' => 'SU'],
            ['name' => 'Suriname', 'code' => 'NS'],
            ['name' => 'Svalbard', 'code' => 'SV'],
            ['name' => 'Swaziland', 'code' => 'WZ'],
            ['name' => 'Sweden', 'code' => 'SW'],
            ['name' => 'Switzerland', 'code' => 'SZ'],
            ['name' => 'Syria', 'code' => 'SY'],
            ['name' => 'Taiwan', 'code' => 'TW'],
            ['name' => 'Tajikistan', 'code' => 'TI'],
            ['name' => 'Tanzania', 'code' => 'TZ'],
            ['name' => 'Thailand', 'code' => 'TH'],
            ['name' => 'Togo', 'code' => 'TO'],
            ['name' => 'Tokelau', 'code' => 'TL'],
            ['name' => 'Tonga', 'code' => 'TN'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TD'],
            ['name' => 'Tunisia', 'code' => 'TS'],
            ['name' => 'Turkey', 'code' => 'TU'],
            ['name' => 'Turkmenistan', 'code' => 'TX'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TK'],
            ['name' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ukraine', 'code' => 'UP'],
            ['name' => 'United Arab Emirates', 'code' => 'AE'],
            ['name' => 'United Kingdom (England, Northern Ireland, Scotland, and Wales)', 'code' => 'UK'],
            ['name' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'code' => 'NH'],
            ['name' => 'Venezuela', 'code' => 'VE'],
            ['name' => 'Vietnam', 'code' => 'VM'],
            ['name' => 'Virgin Islands', 'code' => 'VQ'],
            ['name' => 'Wake Island', 'code' => 'WQ'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF'],
            ['name' => 'Western Sahara', 'code' => 'WI'],
            ['name' => 'Yemen (Aden)', 'code' => 'YM'],
            ['name' => 'Zambia', 'code' => 'ZA'],
            ['name' => 'Zimbabwe', 'code' => 'ZI'],
        ];

        /*
        |--------------------------------------------------------------------------
        | Insert / Update Countries
        |--------------------------------------------------------------------------
        |
        | Custom country codes are preserved.
        |
        */

        Country::upsert(
            $countries,
            ['code'],
            ['name']
        );

        /*
        |--------------------------------------------------------------------------
        | Country-specific Region / Postal Labels
        |--------------------------------------------------------------------------
        */

        Country::where('code', 'US')->update([
            'region_label' => 'State',
            'postal_label' => 'ZIP Code',
        ]);

        Country::where('code', 'CA')->update([
            'region_label' => 'Province',
            'postal_label' => 'Postal Code',
        ]);

        Country::where('code', 'IN')->update([
            'region_label' => 'Locale',
            'postal_label' => 'Postal',
        ]);
    }
}